config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/index'
  get 'home/list'
  get 'home/create'
  post 'home/write'
  
  get 'home/create1'
  get 'home/list1'
  
  get 'home/admin'
  post 'home/admin_access_hjh_9294'
  post 'home/delete'

end

app/models/post.rb
class Post < ActiveRecord::Base
   self.per_page = 10
   
  def self.search(search)
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def list
      @list_country = request.location.country
      temp = params[:button]
      if params[:search]
        @every_post = Post.search(params[:search]).where(country: request.location.country).order("id desc").paginate(:page => params[:page])
      else
        if temp == "1"
          @every_post = Post.where(filter: "1").order("id desc").paginate(:page => params[:page]) 
        else
          @every_post = Post.where(country: request.location.country).where(filter: "0").order("id desc").paginate(:page => params[:page])   
        end
      end

  end
  def count
    @every_post = Post.find(params[:id])
    @every_post.clicks = params[:count_test]
    @every_post.save
    
  #   count = @every_post.clicks+1
  #   @every_post.update_attributes(:clicks=> count)
  #   #other code
  end
    
    #국가가 사용자의 국가인 DB만 가져옴, 늦게 만들어진 순서대로 정렬, 10개 초과 시 페이지 나누기
    
  
  def create
    
    @create_city = request.location.city
    @create_country = request.location.country
    @trip_select = [*1..38].sample
    
  end
  def write
      new_post = Post.new
      new_post.title = params[:title]
      new_post.content = params[:content]
      new_post.people = params[:people]
      new_post.address = params[:address].split('/').last 
      #주소를 불러올때 /로 분할하여 맨 마지막 것을 가져와라
      new_post.country = params[:country]
      new_post.filter = params[:filter]
      new_post.image = params[:image]
      new_post.save
      
      redirect_to :root
  end
  def admin
    
  end
  
  def admin_access_hjh_9294
    if temp = "ghkdwlwnsgur123"
    @every_post = Post.all
    else redirect_to "home/admin"
    end
  end
  
  def delete
    delete_post = Post.find(params[:id])
    delete_post.destroy
    
    redirect_to "home/admin_access_hjh_9294"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<form action="/home/admin_access_hjh_9294" method ="post">
  <input type="text" name="temp">
  <button type="submit">들어가기</button>
</form>

app/views/home/admin_access_hjh_9294.html.erb
<div class="subpage">

	<!-- Three -->
		<section id="three" class="wrapper" style ="background-color: rgb(250, 250, 250);">
			<div class="inner container" >
				<header class="align-center">
					<h2>In <%= @list_country %> </h2>
					<p>Talk with anonymous users </p>
					<p><%= @list_country %>, <%= request.location.city %>에서 접속했습니다</p>
					<a href="/home/list" name="temp" value="1">모두에게 공유된 글 보기</a>
				</header>
				<!--검색기능-->
				<div style="float: left; width: 70%;">
					<%= form_tag(home_list_path, :method => "get", id: "list_search") do %>
				  <%= text_field_tag :search, params[:search], placeholder: "ex) 스키장"%>
				</div>
				<div style="float: left; width: 30%;">
				  <%= submit_tag "검색", :name => nil %>
					<% end %>
				</div>
				<div class="col-md-2"></div>
				<% @every_post.each do |p| %>
				<div class="col-md-8 col-xs-12" style="margin-top: 10px; margin-bottom: 10px; padding-left: 6px; padding-right: 6px; padding-bottom: 6px; padding-top: 6px; background-color:white; border-radius: 5px; box-shadow: 2px 2px 2px #eee;">
					<div align="center" style="background-image: url(../assets/<%= p.image %>.jpg); border:1px solid #fafafa; border-radius:5px; margin-bottom: 5px; background-repeat: no-repeat; height:150px; background-position:center; " class="img-rounded">
						<div align="center middle" style="color :white">
							<h3 style="white; margin-top=5px;"><strong><%= p.title %></strong></h3><br>
							<%= p.people %>
						</div>
					</div>
					<div align="right" style="color: #bbb">
						<!--time_ago-->
						조회수<% unless p.clicks.present? %>
										0
									<% else %>
										<%= p.clicks %>
									<% end %>
						
						&#183;
						<%= p.content %> <br>
						
						<%= p.country %> &#183;
						
						<% if p.created_at > Time.now.beginning_of_day %>
						  <%="#{time_ago_in_words(p.created_at)} 전"%>
						<% else %>
							<%= p.created_at.strftime("%m월 %d일") %>
						<% end %>
						&#183;
						
						
							
								
									
									
									<a href="kakaoopen://join?l=<%= p.address %>&r=EW">
										<button type="submit" class="btn btn-default like_submit test" id="test" style="border:none; background:none; background-color:none">		
											<input name="id_of_article_test" type="hidden" id="article_id_test" value="<%= p.id %>">
											<input name="clicks_of_article_test" type="hidden" id="article_clicks_test" value="<% unless p.clicks.present? %>0<% else %><%= p.clicks %><% end %>">
											참여하기
										</button>
									</a> <!--class="button special"--> 
					</div>
				</div><br>
				<%end%>
				<div class="col-mid-2"></div>
			</div>
			<div align= "center">
			<%= will_paginate @every_post, inner_window: 3, outer_window: 1 %>
			</div>
		</section>

	<!-- Footer -->
		<footer id="footer">
			<div class="inner">
				<div class="copyright">
					&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
				</div>
			</div>
		</footer>
		
</div>

<script type="text/javascript">

			$(".test").on("click", function(){
				
	      var id = $(this).children("#article_id_test").val()
	      var clicks = $(this).children("#article_clicks_test").val()
	      
	      
	      
	        $.ajax({
	        method: "POST",
	        url: "/home/count",
	        data: { count_test: parseInt(clicks) + 1, id: id}
	      });
	    });

</script>

app/views/home/create.html.erb
<div class="subpage">

	<!-- Header -->
		<header id="header">
			<div class="inner">
				<a href="/home/index" class="logo">Ge<strong>O</strong>talk</a>
				<nav id="nav">
					<a href="/home/index">Home</a>
					<a href="/home/list">글목록</a>
					<a href="/home/create">글쓰기</a>
				</nav>
				<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
			</div>
		</header>

	<!-- Main -->
		<section id="main" class="wrapper">
			<div class="inner">
				<header class="align-center">
					<h2>오픈카톡방 공유하기</h2>
					<p>우리 같이 여행해요. </p>
				</header>

			
				여행 지역 : <%= @create_country %> <%= @create_city %>
				<form action="/home/write" method="post">
					<div class="row uniform">
						<div class="6u 12u$(xsmall)">
							<input type="hidden" name="country" value="<%= @create_country %>"/>
							<input type="hidden" name="image" value="<%= @trip_select %>"/>
							<input type="text" name="title" id="demo-name" value="" placeholder="오픈카톡방 이름" required/><br>
							<input type="radio" id="people_1" name="people" value="그룹 대화방" checked>
							<label for="people_1">그룹 대화방</label>
							<input type="radio" id="people_n" name="people" value="1:1 대화방">
							<label for="people_n">1:1 대화방</label>
						</div>
						<div class="6u$ 12u$(xsmall)">
							<input type="text" name="address" id="demo-email" value="" placeholder="오픈카톡방 주소" required/>
							<p>예) https://open.kkao.com/o/g9vkySp <br>  또는 g9vkySp</p>
						</div>
						<div class="12u$">
							<textarea name="content" id="demo-message" placeholder="태그 ex) #숙소 #축구 #유럽여행예정" rows="1" required></textarea>
						</div>
						
						<div class="6u 12u$(small)">
							<input type="radio" id="f_country" name="filter" value="0" checked>
							<label for="f_country">나와 같은 국가의 여행자와 공유</label>
							<input type="radio" id="f_all" name="filter" value="1">
							<label for="f_all">모든 지역의 여행자와 공유</label>
						</div>
						<!-- Break -->
						
						<!-- Break -->
						<div class="12u$">
							<ul class="actions">
								<li><input type="submit" value="오픈카톡 공유하기" /></li>
							</ul>
						</div>
					</div>
				</form>
				<hr/>
			</div>
			<div class="media post-item review   ">
				<div class="media-top post-item-image-wrapper">
					<div class="post-item-image" style="background-image: url(&quot;http://image.reviewrepublic.net/1-r1YyN0fMg.jpg?w=900&amp;&quot;);">
						
					</div>
				</div>
		</section>
		
		<footer id="footer">
			<div class="inner">
				<div class="copyright">
					&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
				</div>

			</div>
		</footer>
</div>

app/views/home/create1.html.erb
	<div class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="index.html" class="logo"><strong>Projection</strong> by TEMPLATED</a>
					<nav id="nav">
						<a href="index.html">Home</a>
						<a href="generic.html">Generic</a>
						<a href="elements.html">Elements</a>
					</nav>
					<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
			</header>

		<!-- Three -->
			<section id="three" class="wrapper">
				<div class="inner">
					<header class="align-center">
						<h2>Nunc Dignissim</h2>
						<p>Aliquam erat volutpat nam dui </p>
					</header>
					<div class="image round left">
						<img src="/assets/pic01.jpg" alt="Pic 01" />
					</div>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>

					<div class="image round right">
						<img src="/assets/pic02.jpg" alt="Pic 02" />
					</div>
					<p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>

					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>

				</div>
			</section>

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">

					<h3>Get in touch</h3>

					<form action="#" method="post">

						<div class="field half first">
							<label for="name">Name</label>
							<input name="name" id="name" type="text" placeholder="Name">
						</div>
						<div class="field half">
							<label for="email">Email</label>
							<input name="email" id="email" type="email" placeholder="Email">
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
						</div>
						<ul class="actions">
							<li><input value="Send Message" class="button alt" type="submit"></li>
						</ul>
					</form>

					<div class="copyright">
						&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
					</div>

				</div>
			</footer>

		<!-- Scripts -->
			<script src="/assets/jquery.min.js"></script>
			<script src="/assets/skel.min.js"></script>
			<script src="/assets/util.js"></script>
			<script src="/assets/main.js"></script>

	</div>

app/views/home/index.html.erb
<!-- Header -->
	<header id="header">
		<div class="inner">
			<a href="/home/index" class="logo">Ge<strong>O</strong>talk</a>
			<!--<nav id="nav">
				<a href="index.html">Home</a>
				<a href="generic.html">Generic</a>
				<a href="elements.html">Elements</a>
			</nav>-->
			<!--.-->
		</div>
	</header>

<!-- Banner -->
	<section id="banner">
		<div class="inner">
			<header>
				<h1>Trip together!!</h1>
			</header>

			<div class="flex ">

				<div>
					<span class="icon fa-car"></span>
					<h3>정보공유</h3>
					<p>같은 나라를 여행하는 타인과 정보를 공유할 수 있습니다.</p>
				</div>

				<div>
					<span class="icon fa-camera"></span>
					<h3>사진공유</h3>
					<p>여행자와 서로의 경험을 나눌 수 있습니다.</p>
				</div>

				<!--<div>
					<span class="icon fa-bug"></span>
					<h3>Ultrices</h3>
					<p>Nulla vitae mauris non felis</p>
				</div>-->

			</div>
      <!-- 내 주변 채팅 -->
			<footer>
			  <!--messagebox
			  <!-- 국내 여행은 추후 개발 합시다 -->
			  			  <!--messagebox-->
				<a href="/home/list" data-confirm="'https://www.geotlak.xyz'에서 현재 위치정보를 사용하고자 합니다" class="button ajax_list">내여행지 오픈카톡</a>
			</footer><br>
			<footer>


				<a href="/home/create" data-confirm="'https://www.geotalk.xyz'에서 현재 위치정보를 사용하고자 합니다" class="button">오픈카톡 공유하기</a>
			</footer>
		</div>
	</section>


<!-- Three -->
	<section id="three" class="wrapper align-center">
		<div class="inner">
			<div class="">
				<article>
					<div class="image round">
						<img src="/assets/pic02.jpg" alt="Pic 01" />
					</div>
					<header>
						<h3>카카오톡의 오픈카톡 서비스를 지역별 공유</h3>
					</header>
  					<p>Geotalk은 지역기반 서비스로서 사용자의 위치를 요청합니다.</p><br>
  					<p>오직 나와 같은 지역에서 여행하는 여행자와 오픈카톡을 공유하여 정보를 나눌 수 있습니다.<p><br>
  					<p>사용자의 지역정보는 오픈카톡 분류의 목적에 이용되며 이외의 용도로는 사용되지 않습니다.</p>
					<footer>
						<a href="/home/list" class="button">내 여행지 오픈카톡 보기</a>
					</footer>
				</article>
				<!--<article>
					<div class="image round">
						<img src="/assets/pic02.jpg" alt="Pic 02" />
					</div>
					<header>
						<h3>Sed feugiat<br /> tempus adipicsing</h3>
					</header>
					<p>Pellentesque fermentum dolor. Aliquam quam lectus<br />facilisis auctor, ultrices ut, elementum vulputate, nunc<br /> blandit ellenste egestagus commodo.</p>
					<footer>
						<a href="#" class="button">Learn More</a>
					</footer>
				</article>-->
			</div>
		</div>
	</section>

<!-- Footer -->
	<footer id="footer">
		<div class="inner">

			
			<div class="copyright">
				&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
			</div>

		</div>
	</footer>

app/views/home/list.html.erb
<div class="subpage">

	<!-- Header -->
		<header id="header">
			<div class="inner">
				<a href="/home/index" class="logo">Ge<strong>O</strong>talk</a>
				<nav id="nav">
					<a href="/home/index">Home</a>
					<a href="/home/list">글목록</a>
					<a href="/home/create">글쓰기</a>
				</nav>
				<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
			</div>
		</header>

	<!-- Three -->
		<section id="three" class="wrapper" style ="background-color: rgb(250, 250, 250);">
			<div class="inner container" >
				<header class="align-center">
					<h2>In <%= @list_country %> </h2>
					<p>Talk with anonymous users </p>
					<p><%= @list_country %>, <%= request.location.city %>에서 접속했습니다</p>
					<a href="/home/list" name="temp" value="1">모두에게 공유된 글 보기</a>
				</header>
				<!--검색기능-->
				<div style="float: left; width: 70%;">
					<%= form_tag(home_list_path, :method => "get", id: "list_search") do %>
				  <%= text_field_tag :search, params[:search], placeholder: "ex) 스키장"%>
				</div>
				<div style="float: left; width: 30%;">
				  <%= submit_tag "검색", :name => nil %>
					<% end %>
				</div>
				<div class="col-md-2"></div>
				<% if @every_post.blank? %>
				    <div align="center" class="col-md-8 col-xs-12">
				    	<p>아직 해당 여행지의 오픈카톡이<br>공유되지 않았습니다.<br>가장 먼저 오픈카톡을 공유해주세요</p>
				    	<a href="/home/create" class="button">오픈카톡 공유하러 가기</a>
				    </div>
				<% else %>
					<% @every_post.each do |p| %>
					<div class="col-md-8 col-xs-12" style="margin-top: 10px; margin-bottom: 10px; padding-left: 6px; padding-right: 6px; padding-bottom: 6px; padding-top: 6px; background-color:white; border-radius: 5px; box-shadow: 2px 2px 2px #eee;">
						<div align="center" style="background-image: url(../assets/<%= p.image %>.jpg); border:1px solid #fafafa; border-radius:5px; margin-bottom: 5px; background-repeat: no-repeat; height:150px; background-position:center; " class="img-rounded">
							<div align="center middle" style="color :white">
								<h3 style="white; margin-top=5px;"><strong><%= p.title %></strong></h3><br>
								<%= p.people %>
							</div>
						</div>
						<div align="right" style="color: #bbb">
							<!--time_ago-->
							조회수<% unless p.clicks.present? %>
											0
										<% else %>
											<%= p.clicks %>
										<% end %>
							
							&#183;
							<%= p.content %> <br>
							
							<%= p.country %> &#183;
							
							<% if p.created_at > Time.now.beginning_of_day %>
							  <%="#{time_ago_in_words(p.created_at)} 전"%>
							<% else %>
								<%= p.created_at.strftime("%m월 %d일") %>
							<% end %>
							&#183;
							
							
								
									
										
										
										<a href="kakaoopen://join?l=<%= p.address %>&r=EW">
											<button type="submit" class="btn btn-default like_submit test" id="test" style="border:none; background:none; background-color:none">		
												<input name="id_of_article_test" type="hidden" id="article_id_test" value="<%= p.id %>">
												<input name="clicks_of_article_test" type="hidden" id="article_clicks_test" value="<% unless p.clicks.present? %>0<% else %><%= p.clicks %><% end %>">
												참여하기
											</button>
										</a> <!--class="button special"--> 
						</div>
					</div><br>
					<%end%>
				<% end %>
				<div class="col-mid-2"></div>
			</div>
			<div align= "center">
			<%= will_paginate @every_post, inner_window: 3, outer_window: 1 %>
			</div>
		</section>

	<!-- Footer -->
		<footer id="footer">
			<div class="inner">
				<div class="copyright">
					&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
				</div>
			</div>
		</footer>
		
</div>

<script type="text/javascript">

			$(".test").on("click", function(){
				
	      var id = $(this).children("#article_id_test").val()
	      var clicks = $(this).children("#article_clicks_test").val()
	      
	      
	      
	        $.ajax({
	        method: "POST",
	        url: "/home/count",
	        data: { count_test: parseInt(clicks) + 1, id: id}
	      });
	    });

</script>

app/views/layouts/application.html.erb
<html>
<head>
  <title>해외여행 지역별 오픈카톡 공유 사이트 : Geotalk</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="/assets/main.css" />
  	<!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>	
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turb olinks-track' => false %>
  <%= csrf_meta_tags %>
  <script src="/assets/jquery.min.js"></script>
  <script src="/assets/skel.min.js"></script>
  <script src="/assets/util.js"></script>
  <script src="/assets/main.js"></script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90232447-1', 'auto');
  ga('send', 'pageview');

  </script>

</head>
<body>

<%= yield %>

</body>
</html>